server:
  port: 8000
  servlet:
    context-path: /video-call/api/

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/meeting_app"
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.ap-southeast-2.amazonaws.com/ap-southeast-2_x1YuRTE27
#          jwk-set-uri: https://cognito-idp.ap-southeast-2.amazonaws.com/ap-southeast-2_x1YuRTE27/.well-known/jwks.json

springdoc:
  api-docs:
    path: /document/api-docs
  swagger-ui:
    path: /document/swagger-ui.html
